language: ruby

sudo: false
cache: bundler

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.9
  - 2.2.0
  - 2.2.6
  - 2.3.1
  - 2.3.3
  - 2.4.0

gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - Gemfile

script:
  - bundle exec rake spec

before_script:
  - bundle exec rake phonelib:create_test_db

after_script:
  - CODECLIMATE_REPO_TOKEN=230dc861ec831b64dc4818a2002de07fbd2a413cc460385eb05958564eb70687 bundle exec codeclimate-test-reporter

matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 1.9.2
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.2.6
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.3.1
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.3.3
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.4.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
